version: '3.1'

services:
  db:
    image: postgres:14.1
    privileged: true
    restart: always
    ports:
      - 54323:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: qwerty
      POSTGRES_DB: test
