# Generated by Django 3.2 on 2021-11-24 09:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('djapp', '0003_alter_product_date_add'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='date_add',
            field=models.DateField(auto_now=True),
        ),
    ]
